# Generated by Django 5.0.4 on 2024-05-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='author',
        ),
    ]
