# Generated by Django 5.0.4 on 2024-05-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_ad_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
