# Generated by Django 5.0.4 on 2024-05-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_alter_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='ad/%Y/%m/%d/'),
        ),
    ]
